Repository XCSoar/XCSoar, pull requests merged in 2018-06, with the labels that each got.

#112 [Android] Make it possible to play external wav files
  android/src/SoundUtil.java
  src/Android/SoundUtil.cpp
  src/Android/SoundUtil.hpp
  src/Audio/Sound.cpp
Labels: enhancement

#109 prevent DownloadFilePicker options from being listed twice
  src/Dialogs/DownloadFilePicker.cpp
Labels: bug, needs-backport

#114 [6.8] prevent DownloadFilePicker options from being listed twice
  src/Dialogs/DownloadFilePicker.cpp
Labels: bug

#110 Update README
  README.rst
  doc/manual/en/XCSoar-developer-manual.tex
Labels: documentation

#75 Added three variants of AllStar SZD54-2 Perkoz
  src/Polar/PolarStore.cpp
Labels: enhancement
